### ISSUE TITLE
Change authorize Texts on Mail registration

### ISSUE THREAD

**Issue by bnjmnsbl** [technologiestiftung/tsb-trees-frontend#14]
Currently this shows up when registering. Is it possible to change it?

![Screen Shot 2020-04-29 at 15 03 29](https://user-images.githubusercontent.com/11134234/80605154-fa444f00-8a32-11ea-9724-3f61222de4d0.png)

**Comment by fabianmoronzirfas** [comment]
@bnjmnsbl Can you make a suggestion what should be customized? I have the possibility the customize everything.

**Comment by fabianmoronzirfas** [comment]
An annotated screenshot would be enough

**Comment by bnjmnsbl** [comment]
Authorization doesn't show up anymore, so everything is fine?
