### ISSUE TITLE
Can I Haz Username?

### ISSUE THREAD

**Issue by bnjmnsbl** [technologiestiftung/tsb-trees-frontend#15]
Can users pick a username on registration, please (right now, registration is only email + pw)? can this be done in Auth0?

Related to [#10 ](https://github.com/technologiestiftung/tsb-trees-frontend/issues/10)

**Comment by fabianmoronzirfas** [comment]
I guess this is the way to go https://auth0.com/docs/connections/database/require-username

**Comment by fabianmoronzirfas** [comment]
Usernames are now required for logging in
