### ISSUE TITLE
Create Impressum

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/tsb-trees-frontend#165]
Links only accessible all the time.

**Comment by julizet** [comment]
just talked to Ben regarding the Impressum.

--> want to keep the referer link to TSB Impressum
--> move "Impressum" & "Datenschutz" between "Teilen auf" and "GitHub"
--> style "Impressum" and "Datenschutz" so its directly visible (keyword: Barrierefreiheit)

**Comment by fabianmoronzirfas** [comment]
Okay. So no additional page? Fine with me. We still need to make it visible and accessible all the time. Means it has to be in the start screen, and in the screen that gets rendered when there is no js. I'm not sure if we can hide it in the slideout menu. This is unaccesible
