### ISSUE TITLE
UI: Extend Trees Detail View Component

### ISSUE THREAD

**Issue by fdnklg** [technologiestiftung/tsb-trees-frontend#2]
Add content:
- Meta Information about the type of tree
- Information about watering

**Comment by bnjmnsbl** [comment]
information about the zuständige grünflächenamt (can be derived from the district that the tree is in...mirko or julia kann research the contact data)

**Comment by mirkohohmann** [comment]
> information about the zuständige grünflächenamt (can be derived from the district that the tree is in...mirko or julia kann research the contact data)

Voilà: https://docs.google.com/spreadsheets/d/17mkHg0jxMxebmN9DnS_suemvQ74kHRMu2r2n-h-hGJM/edit#gid=0
