### ISSUE TITLE
Cookie content

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/tsb-trees-frontend#37]
There is a local storage object being generated with following content: mapbox.eventData:ZmRua2xn:{"lastSuccess":1588594083071,"tokenU":"fdnklg"}

??

**Comment by fabianmoronzirfas** [comment]
@fdnklg any idea?

**Comment by sebastian-meier** [comment]
@fdnklg the cookie itself is no problem for me, but tokenU should either be TSB-related or TREE-related...

**Comment by sebastian-meier** [comment]
@fdnklg as the tokenU does not show up in our code, i think you are using your private mapbox account, i will send you an api-key from the official account...
