### ISSUE TITLE
Add Data Sources

### ISSUE THREAD

**Issue by bnjmnsbl** [technologiestiftung/tsb-trees-frontend#42]
Baumkataster has Nutzungsbedingungen: Für die Nutzung der Daten ist die Datenlizenz Deutschland - Namensnennung - Version 2.0 anzuwenden. Die Lizenz ist über https://www.govdata.de/dl-de/by-2-0 abrufbar. Der Quellenvermerk gemäß (2) der Lizenz lautet "Geoportal Berlin / [Titel des Datensatzes]".

Not sure about DWD data?

**Comment by bnjmnsbl** [comment]
This could be added on the right hand side of the splash screen, where there is currently a lot of whitespace. A link to the GithHub repo would also be nice.

**Comment by fabianmoronzirfas** [comment]
> Copyright [DE](DE/service/copyright/copyright_artikel.html "auf deutsch anzeigen")
> ==================================================================================
> 
> All information on the web pages of the DWD is protected by copyright.
> 
> As laid down in the Ordinance Setting the Terms of Use for the Provision of Federal Spatial Data ([GeoNutzV](http://www.geodatenzentrum.de/docpdf/geonutzv_eng.pdf "External link to The Service Centre of the Federal Government for Geo-Information and Geodesy (DLZ) and the Central Office for Geo-Topography (Opens in new window)")), all spatial data and spatial data services available for free access may be used without any restrictions provided that the source is acknowledged. When speaking of spatial data, this also includes any location-related weather and climate information presented on our open web pages.  
>   
> Any other content presented on DWD web pages, in whole or extracts thereof, may be reproduced, altered, distributed, used or publicly presented only if expressly permitted by the DWD.  
>   
> Rules and templates for acknowledging the DWD as source can be found [here](EN/service/copyright/templates_dwd_as_source.html?nn=495490 "Rules for acknowledging the DWD as source")
> 
> Wherever the DWD uses data or information from third parties to generate new products and services, the DWD assures that it holds all necessary rights to do so.
> 
> Source of basic geospatial data: Surveying authorities of the Länder and Federal Agency for Cartography and Geodesy (BKG) ([http://www.bkg.bund.de](http://www.bkg.bund.de "External link Bundesamt für Kartographie und Geodäsie (Opens in new window)"))
> 
> Sources of satellite data: EUMETSAT ([http://www.eumetsat.int](http://www.eumetsat.int "External link EUMETSAT (Opens in new window)")), NOAA ([http://www.noaa.gov](http://www.noaa.gov "External link National Oceanic and Atmospheric Administration (Opens in new window)"))

[Source](https://www.dwd.de/EN/service/copyright/copyright_artikel.html;jsessionid=0E647F87D5991B25307B026956D2A563.live11054?nn=495490&lsbId=627548)
