### ISSUE TITLE
See user name in profile

### ISSUE THREAD

**Issue by bnjmnsbl** [technologiestiftung/tsb-trees-frontend#49]
If I open my profile page, I'd like to see my username

**Comment by fabianmoronzirfas** [comment]
With the pr #72 we added the [user management api](https://github.com/technologiestiftung/tsb-trees-api-user-management) which allows to nuke 💣☣ users and also get a subset of userdate. 
@fdnklg Can you take over from here or are you busy?

**Comment by fdnklg** [comment]
The user name from the user management api is now available at the profile section.
