### ISSUE TITLE
Kachel mit Slack Channel

### ISSUE THREAD

**Issue by mirkohohmann** [technologiestiftung/tsb-trees-frontend#61]
Statt "mehr erfahren": Mit anderen austauschen: Tritt unserem Slack-Kanal bei, um Dich mit anderen User*innen auszutauschen und die Bewässerung von Bäumen in deinem Kiez zu koordinieren.
https://join.slack.com/t/giessdenkiez/shared_invite/zt-e3et281u-xON4UmBZpKavzDRkw5HmCQ

**Comment by bnjmnsbl** [comment]
We don't need a separate tile for it, just add it on the splash screen where #42 is also added
