### ISSUE TITLE
Splash screen design

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/tsb-trees-frontend#92]
- Logo is cut of on smaller screens
- Splash is over cookie notice on small screens (old scrolling version did not)
- Text review. One of the sentences starts with "Oder"

related to #60 @mirkohohmann did you do the text review?

**Comment by mirkohohmann** [comment]
@fabianmoronzirfas Welcher Satz fängt mit "oder" an? Ich bin gerade den Originaltext bei Google durchgegangen und habe nichts gefunden (https://docs.google.com/document/d/1S61Y5CX_MeAv30IaUDOlO1UPvQz_pGWoYBDctJauXuk/edit#heading=h.gsqqxkibfnf7)

**Comment by fabianmoronzirfas** [comment]
@mirkohohmann Zweiter Satz auf dem splashscreen

**Comment by mirkohohmann** [comment]
@fabianmoronzirfas Wenn du das durchstreichst, heißt das, es ist erledigt?
