### ISSUE TITLE
Notice that the data is from the fis-broker is not enough

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/tsb-trees-frontend#94]
@bnjmnsbl What should we write there?

**Comment by bnjmnsbl** [comment]
1. Remove Section "Plattform und Daten" (in Sidebar/Info) completely.
2. Add at the very bottom (after "Über uns"): 

Datenquellen: 
[Geoportal Berlin / Straßenbäume](https://fbinter.stadt-berlin.de/fb/berlin/service_intern.jsp?id=s_wfs_baumbestand@senstadt&type=WFS)
[Geoportal Berlin / Anlagenbäume](https://fbinter.stadt-berlin.de/fb/berlin/service_intern.jsp?id=s_wfs_baumbestand_an@senstadt&type=WFS)
[Deutscher Wetterdienst](https://www.dwd.de)
Wasserpumpen von [OpenStreetMap](https://www.openstreetmap.de/)
